
---
- name: Install Nginx
  hosts: your_target_host  # Replace with the target host or group
  become: yes

  vars:
    nginx_server_name: 172.31.39.70
    nginx_location: test

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started

    - name: Nginx Conf
      template:
        src: nginx.j2
        dest: /etc/nginx/sites-available/{{ nginx_location }}
      notify: Reload Nginx

    - name: Create symbolic link for Nginx configuration
      file:
        src: /etc/nginx/sites-available/{{ nginx_location }}
        dest: /etc/nginx/sites-enabled/{{ nginx_location }}
        state: link
      notify: Reload Nginx
  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
